#
# Copyright (C) 2021 Elytrium, DoNotSpamPls
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

name: eZProtector
main: net.elytrium.ezprotector.paper.PaperPlugin
version: ${project.version}
authors: [DoNotSpamPls, dvargas135, Gianluca, mdxd44, hevav]
description: Securing your server the easy way!
website: https://github.com/Elytrium/eZProtector
api-version: "1.13"
softdepend: [PlaceholderAPI]

commands:
  ezprotector:
    description: Shows information about the plugin and reloads it.
    aliases: [ezp]
    permission: ezprotector.reload

permissions:
  ezprotector.notify:
    description: Notifies admins about players that try to use illegal commands or join with a blocked mod
    children:
      ezprotector.notify.command: true
      ezprotector.notify.mod: true
  ezprotector.notify.command:
    description: Notifies admins about players that try to use illegal commands
    children:
      ezprotector.notify.command.hiddensyntaxes: true
      ezprotector.notify.command.plugins: true
      ezprotector.notify.command.version: true
      ezprotector.notify.command.custom: true
  ezprotector.notify.command.hiddensyntaxes:
    description: "Notifies about players that try to use a command containing the ':' character"
    default: op
  ezprotector.notify.command.plugins:
    description: Notifies about players that try to see the server version (only if custom-plugins is enabled)
    default: op
  ezprotector.notify.command.version:
    description: Notifies about players that try to see the server version (only if custom-version is enabled)
    default: op
  ezprotector.notify.command.custom:
    description: Notifies about players that try to use a blocked command
    default: op
  ezprotector.notify.mod:
    description: Notifies admins about players that try to join with a mod the plugin blocks
    children:
      ezprotector.notify.mod.fabric: true
      ezprotector.notify.mod.forge: true
      ezprotector.notify.mod.liteloader: true
      ezprotector.notify.mod.rift: true
  ezprotector.notify.mod.fabric:
    description: Notifies about players that try to join while having Fabric installed
    default: op
  ezprotector.notify.mod.forge:
    description: Notifies about players that try to join while having Forge installed
    default: op
  ezprotector.notify.mod.liteloader:
    description: Notifies about players that try to join while having LiteLoader installed
    default: op
  ezprotector.notify.mod.rift:
    description: Notifies about players that try to join while having Rift installed
    default: op
  ezprotector.bypass:
    descrption: Allows the usage of all features blocked by the plugin.
    children:
      ezprotector.bypass.command: true
      ezprotector.bypass.mod: true
  ezprotector.bypass.command:
    description: Allows the usage of all features blocked by the plugin, except for mods
    children:
      ezprotector.bypass.command.tabcomplete: true
      ezprotector.bypass.command.hiddensyntaxes: true
      ezprotector.bypass.command.fake: true
      ezprotector.bypass.command.custom: true
  ezprotector.bypass.command.tabcomplete:
    description: Allows the tab completion of all commands
    default: op
  ezprotector.bypass.command.hiddensyntaxes:
    description: "Allows using commands that contain the : character"
    default: op
  ezprotector.bypass.command.fake:
    description: Allows seeing the real plugins list and server version
    default: op
  ezprotector.bypass.command.custom:
    description: Allows the usage of commands that are blocked by the plugin
    default: op
  ezprotector.bypass.mod:
    description: Allows the usage of all the mods the plugin blocks
    children:
      ezprotector.bypass.mod.5zig: true
      ezprotector.bypass.mod.betterpvp: true
      ezprotector.bypass.mod.bettersprinting: true
      ezprotector.bypass.mod.fabric: true
      ezprotector.bypass.mod.forge: true
      ezprotector.bypass.mod.liteloader: true
      ezprotector.bypass.mod.rift: true
      ezprotector.bypass.mod.schematica: true
      ezprotector.bypass.mod.voxelmap: true
      ezprotector.bypass.mod.wdl: true
  ezprotector.bypass.mod.5zig:
    description: Allows the usage of the 5Zig mod
    default: op
  ezprotector.bypass.mod.betterpvp:
    description: Allows the usage of the BetterPvP mod
    default: op
  ezprotector.bypass.mod.bettersprinting:
    description: Allows the usage of the BetterSprinting mod
    default: op
  ezprotector.bypass.mod.fabric:
    description: Allows logging in while having Fabric installed
    default: op
  ezprotector.bypass.mod.forge:
    description: Allows logging in while having Forge installed
    default: op
  ezprotector.bypass.mod.liteloader:
    description: Allows logging in while having LiteLoader installed
    default: op
  ezprotector.bypass.mod.rift:
    description: Allows logging in while having Rift installed
    default: op
  ezprotector.bypass.mod.schematica:
    description: Allows the usage of the Schematica mod
    default: op
  ezprotector.bypass.mod.voxelmap:
    description: Allows the usage of the VoxelMap mod
    default: op
  ezprotector.bypass.mod.wdl:
    description: Allows the usage of the WorldDownloader mod
    default: op
