# eZProtector | Version ${project.version}
# To see what are the placeholders available to you, read the information page here: https://git.io/vpDio

# This module blocks certain commands from being tab completed
[tab-completion]
    blocked = true
    # If this is set to true, the commands in the list will be THE ONLY ones to be tab completed
    whitelist = false
    commands = [
        "sponge",
        "help",
        "?",
    ]

# This blocks players from using commands such as /minecraft:help or /essentials:warp, since they be used to bypass blocks
[hidden-syntaxes]
    blocked = true
    error-message = "&7[&aeZProtector&7] &4That command syntax is forbidden!"
    # If you add a command to this list, it will not be blocked.
    whitelisted = [
        "whitelisted:commands",
        "with:hidden",
        "syntaxes:here"
    ]

    [hidden-syntaxes.notify-admins]
        enabled = true
        message = "&7[&aeZProtector&7] &e%player% &ftried to use a command with a hidden syntax &4(/%command%)"

    [hidden-syntaxes.punish-player]
        enabled = false
        command = "kick %player% %errormessage%"

# This option allows you to block any command you wish by adding it to the list!
[custom-commands]
    blocked = true
    error-message = "&7[&aeZProtector&7]&f You don't have the permission to use this command! &4(/%command%)"
    commands = [
        "sponge",
        "command_without_slash"
    ]

    [custom-commands.notify-admins]
        enabled = true
        message = "&7[&aeZProtector&7] &e%player% &ftried to use a blocked command &4(/%command%)"

    [custom-commands.punish-player]
        enabled = false
        command = "kick %player% %errormessage%"

# This section allows you to block various mods (and even punish players for some of them!)
[mods]
  5zig = false
  betterpvp = false
  bettersprinting = false
  schematica = false
  voxelmap = false
  wdl = false

  # Extremely finnicky, may kick players with a generic "Disconnected" message
  [mods.fabric]
      block = false
      warning-message = "&7[&aeZProtector&7] &e%player% &ftried to join while having Fabric installed"
      punish-command = "kick %player% &4Fabric usage is not allowed."

  [mods.forge]
    block = false
    warning-message = "&7[&aeZProtector&7] &e%player% &ftried to join while having Forge installed"
    punish-command = "kick %player% &4Forge usage is not allowed."

  [mods.liteloader]
    block = false
    warning-message = "&7[&aeZProtector&7] &e%player% &ftried to join while having LiteLoader installed"
    punish-command = "kick %player% &4LiteLoader usage is not allowed."

  [mods.rift]
    block = false
    warning-message = "&7[&aeZProtector&7] &e%player% &ftried to join while having Rift installed"
    punish-command = "kick %player% &4Rift usage is not allowed."
