name: Java CI with Gradle [PR tests]

on: [ pull_request  ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2.3.1
      with:
        distribution: adopt
        java-version: 1.8
    - name: Cache gradle
      uses: actions/cache@v2.1.6
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-
    - name: Build
      run: ./gradlew build
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: eZProtector
        path: build/libs/eZProtector-*.jar
